# Details
title: You Matter
description: Theme for AAC Info

# Favicon
favicon_32: icon/ace-icon-32x32.png
favicon_192: icon/ace-icon-192x192.png
favicon_180: icon/ace-icon-180x180.png
favicon_270: icon/ace-icon-270x270.png

# Analytics
google_analytics_key:

# Settings
sass:
  sass_dir: _sass
  
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

permalink : /:title  ## disables post output